const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const equalsButton = document.querySelectorAll('[data-equals]')
const numberButton = document.querySelectorAll('[data-equals]')
const numberButton = document.querySelectorAll('[data-equals]')
const numberButton = document.querySelectorAll('[data-number]')
const numberButton = document.querySelectorAll('[data-number]')